# Generated by Django 5.0.4 on 2024-05-12 04:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
        ('producto', '0004_producto_description_alter_producto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='updated',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='pedido.DetallePedido', to='producto.producto'),
        ),
    ]
