# Generated by Django 5.0.4 on 2024-05-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('pedido', '0002_remove_pedido_amount_remove_pedido_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='observaciones',
            field=models.TextField(default='sin observaciones'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
