# Generated by Django 5.0.4 on 2024-05-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
