# Generated by Django 5.0.4 on 2024-04-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200, verbose_name="Nombre")),
                ("image", models.ImageField(upload_to="")),
                ("contact", models.TextField(verbose_name="contacto")),
            ],
        ),
    ]
